@host= http://localhost:1337
@authEndpoint={{host}}/api/v1/auth
@userEndpoint={{host}}/api/v1/me
@auditEndpoint={{host}}/api/v1/audits
@bookEndpoint={{host}}/api/v1/books
@Admin1Authorization=Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImRiM2FjNWJkLWU3NGUtNDRkOS05ZWJiLTU3OTNiZTc3MDUwNSIsIm5hbWUiOiJhZG1pbjEiLCJlbWFpbCI6ImFkbWluMUBleGFtcGxlLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2NTkxNjE5MSwiZXhwIjoxNzY2NTIwOTkxfQ.sJIfkMSx0D_UX3hwYWUJzQDDUEa1weJXFa4H_lcpwJc
@Admin2Authorization=Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImVkY2NkMmNjLTg5NjktNGJhMC04NzNmLTVmN2E4NDRjZmQ0MiIsIm5hbWUiOiJhZG1pbjIiLCJlbWFpbCI6ImFkbWluMkBleGFtcGxlLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2NTkxNzYxMCwiZXhwIjoxNzY2NTIyNDEwfQ.SlHMT2xasvieBckj4vbgsTjf_JgN5wp0Zx-lu-evMEg
@Reviewer1Authorization=Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImU5YTk2ODBlLTRkN2UtNDYyOS1hZGFjLTI3ZmI3ZGExYmExNSIsIm5hbWUiOiJyZXZpZXdlcjEiLCJlbWFpbCI6InJldmlld2VyMUBleGFtcGxlLmNvbSIsInJvbGUiOiJyZXZpZXdlciIsImlhdCI6MTc2NTkwNzIwMywiZXhwIjoxNzY2NTEyMDAzfQ.qKM-a71JudnbBNc07WnEr-RBljJV_PWaulqFQAmu_jg
@Reviewer2Authorization=Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImM1ZGFkZjVlLWEwNTQtNGI1NS04MjZkLTQwZGFmOTFhNTUzMCIsIm5hbWUiOiJyZXZpZXdlcjIiLCJlbWFpbCI6InJldmlld2VyMkBleGFtcGxlLmNvbSIsInJvbGUiOiJyZXZpZXdlciIsImlhdCI6MTc2NTkwNzIxNSwiZXhwIjoxNzY2NTEyMDE1fQ.-X0YOg12GkxM8DJy5WoJqYNeSuwpYArZVmc0nK1nWx0

# Catch all not found route
GET {{host}} HTTP/1.1
###

# Login as admins, update the token in the token variable after login
POST {{authEndpoint}}/login HTTP/1.1
Content-Type: application/json

{
  "email":"admin1@example.com",
  "credentials":"admin123"
}
###

# Get user profile
GET {{userEndpoint}} HTTP/1.1
Authorization: {{Admin1Authorization}}
###

# Get books
GET {{bookEndpoint}} HTTP/1.1
Authorization: {{Admin1Authorization}}
###

# Get book by id
GET {{bookEndpoint}}/7d6fbc7d-c08e-4f48-8eb5-1742da92f957 HTTP/1.1
Authorization: {{Admin1Authorization}}
###

# Create a book
POST {{bookEndpoint}} HTTP/1.1
Authorization: {{Admin1Authorization}}
Content-Type: application/json

{
  "title":"manish",
  "authors": "manish"
}
###

# Update book
PATCH {{bookEndpoint}}/21f78c2a-8e19-4a22-9414-25a209adead3 HTTP/1.1
Authorization:  {{Admin2Authorization}}
Content-Type: application/json

{
  "authors":"satish"
}
###

# Delete book
DELETE {{bookEndpoint}}/594ea7f4-91a8-4949-ad3d-424e9368ed80 HTTP/1.1
Authorization: {{Admin2Authorization}}
###

# Get Audits
GET {{auditEndpoint}}
Authorization: {{Admin1Authorization}}
###

# Get Audit
GET {{auditEndpoint}}/88338282-b9b7-42fd-8837-32700df1a91a HTTP/1.1
Authorization: {{Admin1Authorization}}
